### ISSUE TITLE
Low Framerate On Some Devices

### ISSUE THREAD

**Issue by MrDWilson** [MrDWilson/MobileGame#3]
Testing needs to be done to evaluate the cause of the frame rate drops. The cause could be low power mode, but I have tested on a device and the same problem occured with this turned off. Will post extra testing results.

**Comment by RyanDoesCG** [comment]
Which devices and how bad of a drop? and at what score/difficulty?

**Comment by MrDWilson** [comment]
On every device other than my own, there are some frame rate drops on the current public build. Confusing, but I'm going to run their phones whilst on my mac to see what the analysis is saying. It's a fairly big drop sometimes, and the timing seems completely random.

**Comment by RyanDoesCG** [comment]
even on more recent devices than yours?

**Comment by MrDWilson** [comment]
Yep. My roommates 6s really doesn't react well to the game, and I will get my Mum to look into it more as well (same phone). 
The game is unrunnable on 5 or earlier, but that's just a legacy problem.

**Comment by RyanDoesCG** [comment]
oh wait, did you ever push the 3.1 update? they could be really far behind version wise

**Comment by MrDWilson** [comment]
I'll push it now if you still have a version, is it in a branch?

**Comment by RyanDoesCG** [comment]
let me run it on my phone to confirm but it should be the current beta 3 build. i'll confirm on messenger in a second
