### ISSUE TITLE
New splash screen/icon with colour 

### ISSUE THREAD

**Issue by RyanDoesCG** [MrDWilson/MobileGame#7]
Needs it to be valid for the app store right?

**Comment by MrDWilson** [comment]
Correct. It doesn't like how our icon has no colour (a coloured thrust will fix that), and you mentioned you wanted to max the splash screen to the game? So it blends better?

**Comment by RyanDoesCG** [comment]
yeah, also need to look into changing the backdrop with the difficulty

**Comment by RyanDoesCG** [comment]
done
